image: docker:20.10.8

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:latest"
  KUBE_URL: "https://localhost:6443" 
  KUBE_NAMESPACE: "cloudrift" 
  DEPLOYMENT_NAME: "cloudrift" 

stages:
  - build
  - deploy
 
build:
  stage: build
  # tags:
  #   - home
  script:  
    - docker build -t dev-cloudrift .
    - docker tag dev-cloudrift:latest $IMAGE_TAG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG  
  

deploy:
  stage: deploy
  image: alpine:latest
    # Użyj runnera działącego na klast rze  
  tags:
    - home  
  script:
    - apk add --no-cache kubectl
    # Tworzymy katalog, jeśli nie istnieje
    - mkdir -p /builds/$CI_PROJECT_NAME 
    # Tworzymy plik kubeconfig
    - echo "$KUBECONFIG_DATA" > /builds/$CI_PROJECT_NAME/kubeconfig
    - export KUBECONFIG=/builds/$CI_PROJECT_NAME/kubeconfig
    # Restart aplikacji w Kubernetesie
    - kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $KUBE_NAMESPACE
 