image: docker:20.10.8

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:latest"
  KUBE_URL: "https://10.10.10.10:6443" 
  KUBE_NAMESPACE: "dev-cloudrift" 
  DEPLOYMENT_NAME: "cloudrift-deployment" 

stages:
  - build
  - deploy

build:
  stage: build
  # tags:
  #   - home
  script:
    - docker build -t dev-cloudrift .
    - docker tag dev-cloudrift:latest $IMAGE_TAG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG


deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - home  
  script:
    - apk add --no-cache kubectl
    - kubectl config set-cluster my-cluster --server=$KUBE_URL --insecure-skip-tls-verify=true
    - kubectl config set-credentials deployer --token=$KUBE_TOKEN
    - kubectl config set-context default --cluster=my-cluster --user=deployer --namespace=$KUBE_NAMESPACE
    - kubectl config use-context default
    - kubectl rollout restart deployment/$DEPLOYMENT_NAME



