image: docker:20.10.8

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:latest"
  KUBE_URL: "https://10.10.10.10:6443" 
  KUBE_NAMESPACE: "dev-cloudrift" 
  DEPLOYMENT_NAME: "cloudrift" 

stages:
  - build
  - deploy

build:
  stage: build
  # tags:
  #   - home
  script:
    - docker build -t dev-cloudrift .
    - docker tag dev-cloudrift:latest $IMAGE_TAG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG


deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - home  
  script:
    - apk add --no-cache kubectl
    - echo "$KUBECONFIG_DATA" > /builds/$CI_PROJECT_NAME/kubeconfig
    - export KUBECONFIG=/builds/$CI_PROJECT_NAME/kubeconfig
    - kubectl rollout restart deployment/$DEPLOYMENT_NAME


