  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cloudrift-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: cloudrift
    template:
      metadata:
        labels:
          app: cloudrift
      spec:
        containers:
        - name: cloudrift
          image: registry.gitlab.com/projectcloudrift/cloudrift:latest
          ports:
          - containerPort: 3100
        imagePullSecrets:
        - name: gitlab-registry-secret
 