apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudrift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudrift
  template:
    metadata:
      labels:
        app: cloudrift
    spec:
      containers:
      - name: cloudrift
        image: registry.gitlab.com/projectcloudrift/cloudrift:latest
        ports:
        - containerPort: 3000
        # Adding security context to comply with OpenShift permissions
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000  # Specify a non-root user
      imagePullSecrets:
      - name: gitlab-registry-secret
