apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cloudrift-route
spec:
  host: cloudrift.pl
  to:
    kind: Service
    name: cloudrift-service
  port:
    targetPort: 3000 
  tls:
    termination: edge
